Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
        echo "10.0.0.11  lab" >> /etc/hosts
    SHELL
    
    config.vm.define "lab" do |lab|
      lab.vm.box = "bento/ubuntu-20.10"
      lab.vm.hostname = "lab"
      lab.vm.network "private_network", ip: "10.0.0.11"
      lab.vm.provider "virtualbox" do |vb|
          vb.memory = 1024
          vb.cpus = 1
      end
    end
  end